INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_chiu_trach_nhiem_noi_dung', 'Ông Phạm Từ Liêm', 'Người chịu trách nhiệm nội dung', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_company_name', 'MCV Corporation', 'company name', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_contact_company_address', 'Tầng 16 - Toà nhà TNR, 54A Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa, Thành phố Hà Nội.', 'Địa chỉ', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_contact_company_address_1', 'Tầng 16 - Toà nhà TNR, 54A Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa, Thành phố Hà Nội.', 'Địa chỉ 1', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_contact_company_address_2', 'Tầng 16 - Toà nhà TNR, 54A Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa, Thành phố Hà Nội.', 'Địa chỉ 2', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_dc.created', '2018-05-05', 'dc.created', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_email', 'lovetv@mcv.com.vn', 'Email', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_enterprise', 'Công ty Cổ phần Phát triển Truyền thông Quảng cáo MAC Việt Nam (MCV Corporation)', 'Doanh nghiệp', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_facebook_profile', '{\"app_id\":\"231043600833624\",\"admins\":\"100001376346062\",\"locale\":\"locale\"}', 'Fb Profile', 2);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_googleplus_profile', '{\"profile_author\":\"\"}', 'Google Plus Profile', 2);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_headquarters', 'Tầng 16 - Toà nhà TNR, 54A Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa, Thành phố Hà Nội.', 'Trụ sở', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_hotline', '1900585868', 'chăm sóc khách hàng', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_opensearch', '{\"OutputEncoding\": \"UTF-8\",\"InputEncoding\": \"UTF-8\",\"AdultContent\": false,\"Language\": \"UTF-8\",\"vi-vn\": \"UTF-8\",\"ShortName\": \"LoveTV\",\"LongName\": \"Tìm kiếm thông tin tại LoveTV\",\"Description\": \"Tìm kiếm thông tin tại LoveTV\",\"Tags\": \"clip hot, clip đặc sắc, clip giải trí\",\"Query\": \"clip hot\",\"Developer\": \"Hung NA\",\"Attribution\": \"Search data Copyright 2018, LoveTv.com.vn; All Rights Reserved\",\"SyndicationRight\": \"open\",\"Contact\": \"cskh@gviet.vn\",\"Domain\": \"lovetv.com.vn\"}', 'Open Search', 2);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_phone_number', '024 6275 2435', 'Số điện thoại', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_responsible_person', 'Ông Phạm Từ Liêm', 'chịu trách nhiệm nội dung', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_seo_geo_tagging', '{\"placename\":\"Ha Noi, Viet Nam\",\"region\":\"VN-HN\",\"position\":\"21.0054387,105.8038863\",\"ICBM\":\"21.0054387,105.8038863\"}', 'GEO Tag', 2);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_seo_revisit-after', '1 days', 'revisit-after', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_seo_robots', 'index, follow', 'seo_robots', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_company', 'Công ty Cổ phần Phát triển Truyền thông Quảng cáo MAC Việt Nam (MCV Corporation)', 'Tên cty', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_description', 'Video giải trí, video hay, video hấp dẫn', 'Nội dung mô tả', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_email', 'lovetv@mcv.com.vn', 'Email', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_fax', '686868', 'Site Fax', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_images', 'logo.png', 'Image', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_keywords', 'Video hot, video giải trí', 'Keyword chính của site', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_name', 'Kênh video giải trí hàng đầu', 'Site Name', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_phone', '1900585868', 'Site Phone', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_slogan', 'Video hot, video giải trí', 'Site Slogan', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_slogan_footer', 'Video hot, video giải trí', 'Đời sống sâu bít', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_site_title', 'LoveTV', 'Site Title', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_social_profile_json', '{\"phone\": \"1900585868\",\"fax\": \"1900585868\",\"email\": \"cskh@gviet.vn\",\"facebook\": \"\",\"googleplus\": \"\",\"twitter\": \"\",\"medium\": \"/medium\",\"instagram\": \"\",\"youtube\": \"\"}', 'Json Social Profile', 2);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_web_author', 'HungNA @ LoveTV', 'Web Author', 0);
INSERT INTO `data_news_version_2_config`(`id`, `value`, `label`, `type`) VALUES ('love_tv_dang_ky_kinh_doanh', '0102154249 so Sở KH&ĐT Hà Nội cấp ngày 30/01/2007', NULL, 0);
