# Docker compose by dev@nguyenanhung.com
version: '3'
services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - default

    # NGINX Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - default

    # MySQL Service
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        hostname: mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: hungna
        volumes:
            - mariadb-data:/var/lib/mysql
            - ./docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
        networks:
            - default

    # PHP MyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - mariadb
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=hungna
        ports:
            - "3380:80"
        networks:
            - default

#Volumes
volumes:
    mariadb-data:
        driver: local